# Generated by Django 4.2.7 on 2024-01-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Username',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
