# Generated by Django 4.2.7 on 2024-01-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_rename_totalprice_cartdb_totalprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Totalprice',
            new_name='TotalPrice',
        ),
        migrations.RenameField(
            model_name='cartdb',
            old_name='Username',
            new_name='UserName',
        ),
    ]
